// Portfolio content for Sina Matian's airport departure board.
// Mutate values here to update the board — no other file needs to change.
window.PORTFOLIO_DATA = {
  identity: {
    name: 'SINA MATIAN',
    headline: 'CYBERSECURITY & AI RESEARCHER · 10+ APPROVED BUG BOUNTIES',
    tagline: 'Founder · Independent Security Researcher · CS @ NYU',
    location: 'Los Angeles, California',
    email: 'sina@sinamatian.com',
    github: 'time-attack',
    linkedinUrl: 'https://www.linkedin.com/in/sina-matian-b4210238b/',
    photo: 'assets/photos/sina.jpg',  // drop your headshot here; gradient avatar used as fallback
    about:
      'Cybersecurity researcher, software developer, and entrepreneur with a passion for building impactful products. Founder of SeniorSupportAI.org (a nonprofit helping seniors learn technology) and creator of the Tefillin Timer app used by thousands globally. Experienced in reverse engineering, ethical hacking, AI/ML, and full-stack development. Independent security researcher with 10+ approved bug bounties, having responsibly disclosed vulnerabilities in platforms including Hinge, VibeCode, and Wix.',
    highlights: [
      { label: 'BUG BOUNTIES', value: '10+' },
      { label: 'TEFILLIN DAU', value: '30K+' },
      { label: 'SENIORS SERVED', value: '300+' },
      { label: 'PRESS COVERAGE', value: '3 OUTLETS' },
    ],
    languages: 'Fluent English · Conversational Hebrew',
    activities: 'Level 10 Competitive Gymnast · Varsity Wrestler',
  },
  sections: [
    {
      id: 'education',
      label: 'EDUCATION',
      color: '#7d6fd1',
      icon: '🎓',
      items: [
        {
          id: 'edu-nyu',
          flight: 'EDU 001',
          monogram: 'N',
          logo: 'assets/logos/nyu.svg',
          destination: 'NEW YORK UNIVERSITY',
          subtitle: 'BACHELOR OF ARTS · COMPUTER SCIENCE',
          year: '2026 – 2029',
          status: 'ADMITTED',
          detail: {
            title: 'NEW YORK UNIVERSITY',
            role: 'Bachelor of Arts in Computer Science · May 2026 – Jun 2029',
            hero: 'assets/screenshots/nyu-campus.jpg',
            stats: [
              { label: 'GRADE LEVEL', value: 'SOPHOMORE' },
              { label: 'COLLEGE', value: 'CAS' },
            ],
            body: [
              'Pursuing a B.A. in Computer Science at New York University\'s College of Arts and Science.',
            ],
            links: [
              { label: '→ NYU CAS', href: 'https://cas.nyu.edu', primary: true },
            ],
          },
        },
        {
          id: 'edu-smc',
          flight: 'EDU 002',
          monogram: 'S',
          logo: 'https://www.google.com/s2/favicons?domain=smc.edu&sz=128',
          destination: 'SANTA MONICA COLLEGE',
          subtitle: 'COMPUTER SCIENCE · 4.0 GPA',
          year: '2025 –',
          status: 'NOW',
          detail: {
            title: 'SANTA MONICA COLLEGE',
            role: 'Computer Science · Aug 2025 – Present',
            hero: '',
            stats: [
              { label: 'GPA', value: '4.0' },
              { label: 'STANDING', value: 'FRESHMAN' },
            ],
            body: [
              'Concurrent enrollment in Computer Science coursework at Santa Monica College, maintaining a 4.0 GPA.',
            ],
            links: [],
          },
        },
        {
          id: 'edu-pierce',
          flight: 'EDU 003',
          monogram: 'P',
          logo: 'https://www.google.com/s2/favicons?domain=piercecollege.edu&sz=128',
          destination: 'LOS ANGELES PIERCE COLLEGE',
          subtitle: 'COMPUTER SCIENCE · 4.0 GPA',
          year: '2025 – 2027',
          status: 'NOW',
          detail: {
            title: 'LOS ANGELES PIERCE COLLEGE',
            role: 'Computer Science · Aug 2025 – 2027',
            hero: '',
            stats: [
              { label: 'GPA', value: '4.0' },
              { label: 'STANDING', value: 'FRESHMAN' },
            ],
            body: [
              'Concurrent enrollment in Computer Science coursework at LA Pierce College, maintaining a 4.0 GPA.',
            ],
            links: [],
          },
        },
        {
          id: 'edu-chs',
          flight: 'EDU 004',
          monogram: 'C',
          logo: 'https://www.google.com/s2/favicons?domain=calabasashigh.org&sz=128',
          destination: 'CALABASAS HIGH SCHOOL',
          subtitle: 'AP COMPUTER SCIENCE A & PRINCIPLES',
          year: '2021 – 2025',
          status: 'GRADUATED',
          detail: {
            title: 'CALABASAS HIGH SCHOOL',
            role: 'Aug 2021 – Jun 2025',
            hero: '',
            stats: [],
            body: [
              'Graduated from Calabasas High School. Coursework included AP Computer Science A and AP Computer Science Principles.',
            ],
            links: [],
          },
        },
      ],
    },
    {
      id: 'experience',
      label: 'EXPERIENCE',
      color: '#ed8e2b',
      icon: '✈',
      items: [
        {
          id: 'exp-tefillin',
          flight: 'EXP 001',
          monogram: 'T',
          destination: 'TEFILLIN TIMER',
          subtitle: 'FOUNDER · iOS APP · 30K+ DAU',
          year: '2024 –',
          status: 'LIVE',
          detail: {
            title: 'TEFILLIN TIMER',
            role: 'Founder · Part-time · Dec 2024 – Present · Los Angeles (Remote)',
            hero: 'assets/screenshots/tefillin-timer-home.png',
            stats: [
              { label: 'DAILY ACTIVE USERS', value: '30,000+' },
              { label: 'PRESS OUTLETS', value: '3+' },
              { label: 'TENURE', value: '1 YR 6 MOS' },
              { label: 'PLATFORM', value: 'iOS' },
            ],
            body: [
              'Built and launched a free iOS app, helping people track tefillin wrapping with custom reminders and prayer guides.',
              'Grew the app to 30,000+ Daily Active Users.',
              'Secured coverage in 3+ major international outlets including AP News, Jerusalem Post, and i24 News.',
              'Designed and shipped all UI/UX, notification systems, and backend infrastructure solo from the ground up.',
            ],
            links: [
              { label: '→ APP STORE', href: '#', primary: true },
              { label: '→ AP NEWS', href: '#' },
              { label: '→ JERUSALEM POST', href: '#' },
              { label: '→ i24 NEWS', href: '#' },
            ],
          },
        },
        {
          id: 'exp-seniorsupport',
          flight: 'EXP 002',
          monogram: 'S',
          logo: 'https://www.google.com/s2/favicons?domain=seniorsupportai.org&sz=128',
          destination: 'SENIORSUPPORTAI.ORG',
          subtitle: 'FOUNDER · NONPROFIT · 10+ CENTERS',
          year: '2024 –',
          status: 'LIVE',
          detail: {
            title: 'SENIORSUPPORTAI.ORG',
            role: 'Founder · Dec 2024 – Present · 1 yr 6 mos',
            hero: 'assets/screenshots/seniorsupport-home.png',
            stats: [
              { label: 'SENIOR CENTERS', value: '10+' },
              { label: 'SENIORS SERVED', value: '300+' },
              { label: 'VOLUNTEER TEAM', value: '20+' },
              { label: 'CURRICULUM TRACKS', value: '4' },
            ],
            body: [
              'Founded and scaled a nonprofit to 10+ senior centers across Los Angeles, providing hands-on tech education to 300+ seniors.',
              'Built a 20+ person volunteer and technician team, managing all onboarding, scheduling, and training operations.',
              'Developed 4 curriculum tracks covering iPhone, Android, online safety, and cybersecurity fundamentals.',
              'Drove 100% of partnerships, community outreach, and program design from launch with no external funding.',
            ],
            links: [
              { label: '→ SENIORSUPPORTAI.ORG', href: 'https://SeniorSupportAI.org', primary: true },
            ],
          },
        },
        {
          id: 'exp-research',
          flight: 'EXP 003',
          monogram: 'I',
          destination: 'INDEPENDENT SECURITY RESEARCHER',
          subtitle: 'SELF-EMPLOYED · 10+ DISCLOSURES',
          year: '2023 –',
          status: 'NOW',
          detail: {
            title: 'INDEPENDENT SECURITY RESEARCHER',
            role: 'Self-Employed · 2023 – Present · 3 yrs 5 mos',
            hero: 'assets/screenshots/research-banner.png',
            stats: [
              { label: 'DISCLOSURES', value: '10+' },
              { label: 'TRACK RECORD', value: '100% RESPONSIBLE' },
            ],
            body: [
              'Independently discovered and responsibly disclosed 10+ security vulnerabilities across platforms including Hinge, VibeCode, and Wix, earning formal acknowledgment from each company.',
              'Identified critical authentication flaws, insecure API endpoints, and logic-bypass vulnerabilities with real-world exploitability.',
              'Maintained a 100% responsible disclosure track record — all findings reported directly to vendor security teams before any public exposure.',
              'Applied skills in manual testing, Burp Suite, API fuzzing, and reverse engineering to uncover bugs missed by internal security teams.',
            ],
            links: [
              { label: '→ SEE WRITEUPS', href: '#bug-hinge', primary: true },
            ],
          },
        },
        {
          id: 'exp-webutation',
          flight: 'EXP 004',
          monogram: 'W',
          logo: 'https://www.google.com/s2/favicons?domain=webutation.net&sz=128',
          destination: 'WEBUTATION, INC',
          subtitle: 'SOFTWARE ENGINEER INTERN · LEAD DEV ON MVP',
          year: '2022 – 2024',
          status: 'DONE',
          detail: {
            title: 'WEBUTATION, INC',
            role: 'Software Engineer Intern · Dec 2022 – Dec 2024 · 2 yrs 1 mo',
            hero: 'assets/screenshots/webutation-arch.png',
            stats: [
              { label: 'PLATFORMS REVERSED', value: '8' },
              { label: 'CHAINED NETWORKS', value: '4' },
              { label: 'ROLE', value: 'LEAD DEV (MVP)' },
            ],
            body: [
              'Reverse engineered 8 social media platforms (including authentication flows, private APIs, and data pipelines) to build a cross-platform content intelligence system spanning 4 networks.',
              'Designed and implemented a chaining architecture that linked reverse-engineered data across 4 separate platforms, enabling unified analysis not possible through official APIs.',
              'Trained AI/ML models to detect harmful and inappropriate content at scale, improving moderation accuracy across the platform.',
              'Served as lead developer for the MVP; pitched to VC firms across multiple international cities including trips to the Middle East.',
              'Collaborated directly with founders on architecture, product roadmap, and algorithm design as the sole founding engineer.',
            ],
            links: [],
          },
        },
      ],
    },
    {
      id: 'research',
      label: 'RESPONSIBLE DISCLOSURES',
      color: '#c9432f',
      icon: '🛡',
      items: [
        {
          id: 'bug-hinge',
          flight: 'BUG 001',
          monogram: 'H',
          logo: 'assets/logos/hinge.svg',
          destination: 'HINGE',
          subtitle: 'PAYWALL BYPASS · FULL WRITEUP',
          year: '2024',
          status: 'DISCLOSED',
          detail: {
            title: 'HINGE · PAYWALL BYPASS',
            role: 'Responsible Disclosure · 2024',
            hero: 'assets/screenshots/hinge-bypass-1.png',
            stats: [
              { label: 'SEVERITY', value: 'HIGH' },
              { label: 'STATUS', value: 'ACKNOWLEDGED' },
            ],
            body: [
              'Discovered a flaw in Hinge\'s premium paywall that allowed access to gated features without payment. Reported through responsible disclosure; full writeup published.',
            ],
            links: [
              { label: '→ FULL WRITEUP', href: 'blog-hinge-paywall-bypass.html', primary: true },
            ],
          },
        },
        {
          id: 'bug-wix',
          flight: 'BUG 002',
          monogram: 'W',
          logo: 'assets/logos/wix.svg',
          destination: 'WIX.COM',
          subtitle: 'IDOR · USER-SCOPED DATA EXPOSURE',
          year: '2024',
          status: 'DISCLOSED',
          detail: {
            title: 'WIX.COM · IDOR',
            role: 'Responsible Disclosure · 2024',
            hero: 'assets/screenshots/wix-idor-1.png',
            stats: [
              { label: 'SEVERITY', value: 'HIGH' },
              { label: 'STATUS', value: 'ACKNOWLEDGED' },
            ],
            body: [
              'Insecure direct object reference (IDOR) on Wix.com that exposed user-scoped data through predictable endpoints. Reported through responsible disclosure.',
            ],
            links: [
              { label: '→ FULL WRITEUP', href: 'blog-wix-idor.html', primary: true },
            ],
          },
        },
        {
          id: 'bug-vibecode',
          flight: 'BUG 003',
          monogram: 'V',
          logo: 'https://www.google.com/s2/favicons?domain=vibecode.com&sz=128',
          destination: 'VIBECODE',
          subtitle: 'SSH AUTH BYPASS · CRITICAL',
          year: '2024',
          status: 'DISCLOSED',
          detail: {
            title: 'VIBECODE · SSH BYPASS',
            role: 'Responsible Disclosure · 2024',
            hero: 'assets/screenshots/vibecode-ssh-1.png',
            stats: [
              { label: 'SEVERITY', value: 'CRITICAL' },
              { label: 'STATUS', value: 'ACKNOWLEDGED' },
            ],
            body: [
              'Authentication bypass in the Vibecodeapp app\'s SSH flow allowing unauthorized access. Reported through responsible disclosure.',
            ],
            links: [
              { label: '→ FULL WRITEUP', href: 'blog-vibecode-ssh.html', primary: true },
            ],
          },
        },
      ],
    },
    {
      id: 'work',
      label: 'OTHER EXPERIENCE',
      color: '#9a9385',
      icon: '☕',
      muted: true,
      items: [
        {
          id: 'wrk-starbucks',
          flight: 'WRK 001',
          monogram: 'SB',
          logo: 'assets/logos/starbucks.svg',
          destination: 'STARBUCKS',
          subtitle: 'BARISTA · FULL-TIME',
          year: '2024',
          status: '8 MOS',
          detail: {
            title: 'STARBUCKS',
            role: 'Barista · Full-time · May 2024 – Dec 2024 · Los Angeles (On-site)',
            hero: '',
            stats: [],
            body: [
              'Full-time barista at Starbucks. Managed inventory and customer service.',
              'Specialty Coffee and Barista certified.',
            ],
            links: [],
          },
        },
        {
          id: 'wrk-sloans',
          flight: 'WRK 002',
          monogram: 'SL',
          logo: 'https://www.google.com/s2/favicons?domain=sloansicecream.com&sz=128',
          destination: 'SLOAN\'S ICE CREAM LLC',
          subtitle: 'FOOD VENDOR · PART-TIME',
          year: '2022 – 2023',
          status: '18 MOS',
          detail: {
            title: 'SLOAN\'S ICE CREAM LLC',
            role: 'Food Vendor · Part-time · Jul 2022 – Dec 2023 · Los Angeles (On-site)',
            hero: '',
            stats: [],
            body: [
              'Part-time food vendor at Sloan\'s Ice Cream LLC. Food Service and Food and Beverage Operations.',
            ],
            links: [],
          },
        },
      ],
    },
  ],
};
